spring:
  application:
    name: nacos-config

nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: af24bcf1-6f21-498d-90bf-465ed1d02ac6
    data-ids: loamen-config-demo.yaml

server:
  port: 8800
