spring:
  application:
    name: nacos-config

nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: d4404c96-028d-4fb9-a722-d87825e63e65
    data-ids: loamen-config.yaml

server:
  port: 8800
